trigger:
  branches:
    include:
      - main

pr: none


variables:
  NodeVersion: '20.x'

stages:
- stage: Main
  displayName: Main CI
  jobs:
  - job: BuildAndTest
    pool:
      name: self-hosted-linux
    steps:
    - template:  ./templates/install.yml
      parameters:
        nodeVersion: $(NodeVersion)

    - template:  ./templates/ci.yml
    - template:  ./templates/test.yml
    - template:  ./templates/build.yml
