trigger:
  branches:
    include:
      - main

variables:
  NodeVersion: '20.x'

stages:
- stage: Main
  displayName: Main CI
  jobs:
  - job: BuildAndTest
    pool:
      name: self-hosted-linux
    steps:
    - template: ./templates/npm/install.yml
      parameters:
        nodeVersion: $(NodeVersion)

    - template: ./templates/npm/ci.yml
    - template: ./templates/npm/test.yml
    - template: ./templates/npm/build.yml
