trigger: none

pr:
  branches:
    include:
      - main
variables:
  NodeVersion: '20.x'

stages:
- stage: pr
  displayName: PR Pipeline
  jobs:
  - job: BuildAndTest
    pool:
      name: self-hosted-linux
    steps:
    - template:  ./templates/install.yml
      parameters:
        nodeVersion: $(NodeVersion)

    - template:  ./templates/ci.yml
    - template:  ./templates/test.yml
    - template:  ./templates/build.yml
